
os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode7.3
install:
  - eval "$(curl -sL https://raw.githubusercontent.com/Zewo/Zewo/5254525d9da56df29346fd76e99529c22034d61d/Scripts/install-swiftenv.sh)"
script:
  - swift build --fetch # clones all dependencies
  - rm -rf Packages/*/Tests # deletes dependency's tests until duplicate Package.tests issue can be resolved in SPM. At that point, remove.
  - swift build -Xlinker -rpath -Xlinker $(pwd)/.build/debug/
  - swift build --configuration release -Xlinker -rpath -Xlinker $(pwd)/.build/release/
  - swift test
